### ISSUE TITLE
Remove exception catching in build.clj

### ISSUE THREAD

**Issue by tomfaulhaber** [tomfaulhaber/excel-templates#17]
As pointed out by @deobald, we let exception swallowing sneak into build.clj while we were adding features during the winter. This should have been eliminated before we released.

I'm in the midst of resolving #13, so I have all sorts of crazy debug code in there right now, but I'll clean this us as soon as I resolve the other.

Because I'm going to do this, #15 is no longer meaningful.

**Comment by deobald** [comment]
Hey @tomfaulhaber! I've been away traveling (for what was apparently much too long) but it's great to see this now that I'm back. :) Cheers!

**Comment by deobald** [comment]
Oh. I should look more carefully. @tomfaulhaber: Any estimate on when this will be committed/released?
