### ISSUE TITLE
Some excel file as template would not get data inserted

### ISSUE THREAD

**Issue by yubrshen** [tomfaulhaber/excel-templates#19]
With the example below:
(excel/render-to-file
                                    "squares-template-NG.xlsx"
                                    "d:/tmp/squares.xlsx"
   {"Squares" {1 [[1 1]
                 [2 4]
                 [3 9]]}})

No data would be inserted in d:/tmp/squares.xlsx
it would be just a copy of the template without data inserted. 
The template file is "squares-template-NG.xlsx" attached. 

I tried with the template of the example of porfolio, and modify to the example of squares, it worked with computed data inserted. 

(excel/render-to-file
                                    "d:/yushen/dev/clojure/excel-template-try/resources/squares-template-working.xlsx"
                                    "d:/tmp/squares.xlsx"
   {"Squares" {1 [[1 1]
                 [2 4]
                 [3 9]]}})

The template file quares-template-working.xlsx is also attached.

**Comment by tomfaulhaber** [comment]
@yubrshen I'm sorry, I don't think the files got attached right.

**Comment by yubrshen** [comment]
I've just forked your example in order to share the sample template files. Please check here:
https://github.com/yubrshen/excel-templates-example/commit/74bb7c3a932fe80ef5258f0be0d11c9d431ea575

I created the excel file as template using MS Excel 2013 on Windows 7. 

(I can't attach file here, as it requires write permission to the repository.)
