### ISSUE TITLE
Templating for formula =sum(A2:C2) for multiple rows would have value of =sum(A2:C3) for the row below

### ISSUE THREAD

**Issue by yubrshen** [tomfaulhaber/excel-templates#21]
The expected value should be =sum(A3:C3)

Here is the expression to reproduce the problem:
```
(excel/render-to-file "d:/yushen/dev/clojure/excel-templates-example/resources/row-sum.xlsx" "d:/yushen/dev/clojure/excel-templates-example/resources/row-sum-instantiated.xlsx" {"Squares" {1 [[1 1 1]
                 [1 1 1]
                 [1 1 1]]}})
```
The template and the result can be found here:
https://github.com/yubrshen/excel-templates-example/commit/c23720bd7cc1ae114a59321271d7a6e6fbc731c8

**Comment by tomfaulhaber** [comment]
Ah, yes. We keep the beginning of ranges glued to the top, on the assumption that they expand vertically (as in column sums). We can probably be smart about this one when the sum crosses multiple columns.

**Comment by yubrshen** [comment]
Hi Tom,

Thanks for helping me to fix this!

Yu

**Comment by tomfaulhaber** [comment]
@yubrshen Thanks for the bug report. This is a good fix to have in and I think it will be useful to lots of folks.
