### ISSUE TITLE
Sharing violation on Windows when running report from REPL

### ISSUE THREAD

**Issue by smahood** [tomfaulhaber/excel-templates#23]
Windows 10, Excel 2016

- Run a report in the REPL
- Open template file in Excel, make some changes and try to save
- Get error "Your changes could not be saved to <filename> because of a sharing violation. Try saving to a different file
- After closing REPL, excel is able to save to the template file again

I'm going to see if I can pinpoint where the problem is and fix it.

**Comment by smahood** [comment]
Any chance of getting this issue looked at? I've been using it in production for a few months now and it's been working well, but haven't tested it on any other versions of Excel or anything other than Windows.

**Comment by tomfaulhaber** [comment]
@smahood I've pulled your code which looked good. I'll try to push out a release with this in it soon.
