### ISSUE TITLE
Does not copy to template past edited area

### ISSUE THREAD

**Issue by smahood** [tomfaulhaber/excel-templates#27]
Not sure if this is a big deal or not, I've run into it a number of times but there is an easy workaround.

Steps to reproduce
- Create new .xlsx file, do not open or change it
- Run `(let [template-file "new-file.xlsx"
output-file "output-file.xlsx"
data {"Sheet1" [{2 [[1 2]]}]}]
(render-to-file template-file output-file data))
`
- The output file should be blank

To work around the problem, simply open the template file and edit a cell below the lowest row that you expect to be populated - it seems like any non-blank value will work.

**Comment by tomfaulhaber** [comment]
Fixed in 082c83c1076085b25bcd359ea7b0d38e3f7730f4

**Comment by tomfaulhaber** [comment]
Fixed in 082c83c1076085b25bcd359ea7b0d38e3f7730f4
