### ISSUE TITLE
Cloning sheets with charts on them causes a corrupted workbook to result

### ISSUE THREAD

**Issue by tomfaulhaber** [tomfaulhaber/excel-templates#7]
When we clone a worksheet that has a chart on it with POI, it seems to clobber the drawing object for the new worksheet. This causes two problems: (1) I can't get the handle to the chart to transform it into the new context and (2) Excel considers the worksheet to be corrupt and deletes the new worksheet after complaining.

Looking at the worksheet XML after it's saved, I can see that the drawing object has been messed up. The corruption is not visible through the POI API before we save the file - it just appears that the sheet has no drawing object.

I think that I need to save the file and reopen it, then delete the corrupt drawing object and add any charts back in. Blech!

**Comment by dgrnbrg** [comment]
This would be a pretty awesome feature though :) I'd like to use it to auto-generate analytic workborks to compare multiple datasets.

**Comment by tomfaulhaber** [comment]
Just for reference, this bug is captured in the POI buglist as: https://bz.apache.org/bugzilla/show_bug.cgi?id=54470 and is still open, so a new version of POI won't help us (at least not right now).

**Comment by tomfaulhaber** [comment]
This turns out to be even nastier than I thought because POI won't let me delete the charts at the beginning. I might be able to route through the underlying CT object, but my guess is that I'll actually need to edit the zip file and it's XML directly and clean the original charts out that way.

**Comment by tomfaulhaber** [comment]
This is mostly working on the clone-charts branch and had been pushed to clojars as 0.3.2-SNAPSHOT. The remaining part is to deal with charts later in the workbook that reference earlier sheets that get cloned.

I'm interested in any testing anyone wants to do on this snapshot.
