### ISSUE TITLE
A couple questions from Clojure West talk

### ISSUE THREAD

**Issue by smahood** [tomfaulhaber/excel-templates#8]
After watching your talk at Clojure West, I'm planning on replacing our current reporting solution with excel-templates and had a couple questions, both for clarification on the current design and as possibilities for future contributions. If there's a better place for these please let me know.

- Zero based indexes - is there a particular reason for this? It seems like starting at 1 would line up easier with Excel, although otherwise I much prefer zero based indexing.
- Data expansion - is it possible to expand data horizontally as well as vertically? One use case I can think of is to allow multiple month columns on a financial report.
- Passing data in as a map - would it be possible or desirable to extend the functionality to allow passing in of data as a map specifying cell positions (not as a replacement for vectors, but as an addition)? I can totally see myself miscounting nils over and over, and it might be especially useful for dashboard style reports.

I'm hoping to get some time to dive in to the library in the next couple of weeks, it looks like a great solution for a lot of the business reporting pains I've had in the past.

**Comment by tomfaulhaber** [comment]
Hi Shaun,

In general, it's probably best to ping me on twitter (@tomfaulhaber) and 
we can take a more detailed conversation offline. However, these 
questions all seem like they might be of more general interest, so maybe 
it's just as well that we capture the answers here.

>   * Zero based indexes - is there a particular reason for this? It
>     seems like starting at 1 would line up easier with Excel, although
>     otherwise I much prefer zero based indexing.
>
The zero-based indexing is what Apache POI uses (that's the library that 
excel-templates is based on) and I just followed their lead. I have 
mixed feelings about that choice for the reasons you suggest.
>
>   * Data expansion - is it possible to expand data horizontally as
>     well as vertically? One use case I can think of is to allow
>     multiple month columns on a financial report.
>
Not yet, but I plan to do it at some point. I don't know exactly when 
I'll get to it, though, and this might be a good area for someone else 
to contribute. If someone's interested in taking a stab at it, please 
talk to me first as I already have syntax and stuff sketched out for it.
>
>   * Passing data in as a map - would it be possible or desirable to
>     extend the functionality to allow passing in of data as a map
>     specifying cell positions (not as a replacement for vectors, but
>     as an addition)? I can totally see myself miscounting nils over
>     and over, and it might be especially useful for dashboard style
>     reports.
>
Yeah, this is one of those areas where the best syntax will really 
depend on the use case. I'm generally inclined to have a single syntax 
with some "degenerate" versions for simple cases and not provide 
alternate syntaxes which could be confusing. The version I've chosen is 
likely to be somewhat terser in most real world scenarios which I think 
makes the code read more transparently (as in the last example I gave in 
my talk).

That said, it's pretty trivial to provide an alternate syntax via a 
wrapper function and I definitely suggest you do that if it makes your 
use case read more clearly. If it seems like lots of folks were 
preferring such an alternate syntax in the future I might me inclined to 
add such a wrapper directly to the library.
>
> I'm hoping to get some time to dive in to the library in the next 
> couple of weeks, it looks like a great solution for a lot of the 
> business reporting pains I've had in the past.
>

Cool. Feel free to ask anymore questions that you have.

Tom

**Comment by smahood** [comment]
Wrappers are a great idea, I'll experiment with some thoughts and see what feels the most natural once I get working with it. Conceptually, I think it would be great to have everything the end user deals with feel like a natural intersection of clojure and excel, without having any leakage from POI. I'll let you know when if I can come up with anything as I start working with the library.
